### ISSUE TITLE
Reporter ion signal disappears post Monocle run

### ISSUE THREAD

**Issue by amakaju** [gygilab/Monocle#27]
After running monocle with following in command line for a raw file with ddMS2 for TMT16 pleX (MS1 at 60K and Ms2 at 45K)
c:\Monocle.CLI.exe -f TMT16pro.raw -t mzxml
the reporter ion intensities for half of the TMT reporter ions are missing intensities.
The raw file was analyzed in pd2.5

**Comment by amakaju** [comment]
> Hi @amakaju,
> For clarification, do you mean that half of the scans are completely missing TMT reporter information or that within a scan, half of the reporter intensities are missing?

half of the reporter intensities within a scan are missing.

**Comment by mammmals** [comment]
OK, thanks for the extra info. I ran a few TMTpro samples through the latest release and I can't seem to reproduce the lack of reporter ions based off of processing some recent scans. 

In practice, we don't do anything to change the peaks themselves (m/z and intensity) in any of the scans. We merely write them to the mzXML schema and update the precursorMass attribute. Using an mzXML viewer rather than the PD output (I was looking directly at the mzXML peaks using `mzR`), are you able to see the m/z and intensity for the centroided peaks?

**Comment by amakaju** [comment]
would you please provide the cmd command you used for the analysis and the version is the same that is in github i assume. Just to ensure I am using the same command. On second thought the issue might be with PD itself. I will test the output with Msfragger or MAxquant to validate that. Thanks for the help

**Comment by mammmals** [comment]
Yes, happy to. I pulled the latest release: https://github.com/gygilab/Monocle/releases/tag/v0.3.379849338.19

Then I ran: `.\Monocle.CLI.exe -f .\FILE.raw -t mzxml`

We would be interested to hear if using MSFragger/MQ solves the issue, we can add this to the `README` going forward and try to track down the culprit with PD analyses.

**Comment by amakaju** [comment]
After few iterative analysis, I have found that both mzXML and Mzml format is not compatible with the PD 2.5 workflow. The mzml format gives an error from the get-go. the monocle mzml version is around 1.X.X while the mzml version from msconvert/PD 2.5 is around 3.X.X.  Regarding mzxml file the PD pipeline cannot read the scan headers in the way that would facilitate the analysis.

**Comment by mammmals** [comment]
The latest mzML schema I know of is 1.1: https://github.com/HUPO-PSI/mzML/tree/master/schema
We can take a look at the header nodes for the mzXMLs that may be missing for integration with PD. I would guess these are instrument specifiers.
