### ISSUE TITLE
Precursor scan number assignment issues

### ISSUE THREAD

**Issue by amakaju** [gygilab/Monocle#28]
After running monocle with following in command line for a raw file with ddMS2 for TMT16 pleX (MS1 at 60K and Ms2 at 45K) to carry out a correction in only MS1 precursors
c:\Monocle.CLI.exe -f TMT16pro.raw -m 1 -t mzxml
I get following error:
Scan X does not have a precursor scan number assigned for all of the Ms2 scans.
The mzxml thus produced cannot be analyzed in PD 2.5 for the quantitation. The identification portion of the search produces results but the quant portion fails.

**Comment by mammmals** [comment]
Hi @amakaju,
I believe this bug is due to how your specifying the MSorder correction. To correct the precursors for MS2 scans, the `-m` tag needs to be set to `2` or run without specification (your specifying the scans to look for that have precursors).

Specifying `-m 1` would be for tSIM like scans as these are sometimes considered to have an MSorder of 1 (I could recreate the issue you were seeing when I did this on some Exploris data). Can you try running the same with `-m 2` or no specification and see if the error goes away?
